defaults:
  - _self_
  - hydra: gpu_dev
  - override hydra/launcher: submitit_slurm

hydra:
   callbacks:
     log_job_return:
       _target_: hydra.experimental.callbacks.LogJobReturnCallback

benchmark:
    _target_: metalearning_benchmarks.line_sine1d_benchmark.LineSine1D
    n_datapoints_per_task: 16
    n_task: 1024
    output_noise: 0.1
    seed_noise: 1237
    seed_task: 5
    seed_x: 123
model:
    num_steps: 16
    x_dim: 1
    y_dim: 1
    c_dim: 2
    z_dim: 2
    h_dim: 64
    h_dim_dec: 64
    num_layers_enc: 6
    num_layers_ctrl: 6
    num_layers_sched: 6
    num_layers_dec: 6
    num_blocks: 1
    non_linearity: GELU
    self_attn_num_heads: 8
    max_context_size: 16
    context_variant: mean
    model_variant: dis
    noise_variant: free
    noise_max: 1
    noise_min: 0.01
    contextual_schedules: true
training:
    trainer_variant: cntxt
    batch_size: 128
    num_subtasks: 32
    num_val_tasks: 32
    num_samples: 100
    max_context_size: 16
    learning_rate: 0.0001
    num_epochs: 4000
    max_clip_norm: 1.0
    alpha: null
    seed: 0
wandb:
    logging: true
    project: cluster-dvinp-new