common:
  x_dim: 1
  y_dim: 1
  c_dim: 2
  z_dim: 2
  h_dim: 64
  num_layers: 3
  non_linearity: SiLU

dvi_process:
  variant: DIS
  num_steps: 16
  is_cross_attentive: false

set_encoder:
  aggregation: max
  use_context_size: false
  is_attentive: true

decoder:
  has_lat_path: true
  has_det_path: false
  is_cross_attentive: false

training:
  num_epochs: 6000
  batch_size: 1024
  learning_rate: 3e-4
  wandb_logging: false

benchmark:
  package: line_sine1d_benchmark
  name: LineSine1D
  n_task: 4096
  n_datapoints_per_task: 64
  output_noise: 0.1
  seed_task: 1237
  seed_x: 123
  seed_noise: 1237