benchmark:
    _target_: metalearning_benchmarks.line_sine1d_benchmark.LineSine1D
    n_datapoints_per_task: 64
    n_task: 4096
    output_noise: 0.1
    seed_noise: 1237
    seed_task: 1237
    seed_x: 123
common:
    x_dim: 1
    y_dim: 1
    c_dim: 2
    z_dim: 2
    h_dim: 64
    num_layers: 6
    non_linearity: SiLU
control:
    is_cross_attentive: false
    num_heads: null
decoder:
    has_lat_path: true
    has_det_path: false
    is_cross_attentive: false
    num_heads: null
cdvi:
    _target_: src.components.dvi.dis.DIS
    num_steps: 16
set_encoder:
    aggregation: max
    is_attentive: false
    num_heads: null
    use_context_size_emb: false
training:
    batch_size: 128
    learning_rate: 0.0003
    num_epochs: 3000
    alternating_ratio: null
    num_val_tasks: 32
    max_clip_norm: 0.5
    alpha: 1.0
wandb:
    logging: true
    project: dvi-np-cluster
