benchmark:
    _target_: metalearning_benchmarks.sinusoid1d_benchmark.Sinusoid1D # sinusoid1d_benchmark.Sinusoid1DFreq # line_sine1d_benchmark.LineSine1D
    n_datapoints_per_task: 64
    n_task: 4096
    output_noise: 0.1
    seed_noise: 1237
    seed_task: 1237
    seed_x: 123
model:
    x_dim: 1
    y_dim: 1
    c_dim: 2
    z_dim: 8
    h_dim: 32
    num_layers: 3
    non_linearity: GELU
    self_attn_num_heads: null
    cross_attn_num_heads: null
    max_context_size: null
    context_variant: bca
    model_variant: lnp
training:
    trainer_variant: data
    batch_size: 128
    num_subtasks: 32
    num_val_tasks: 32
    num_samples: 100
    max_context_size: 64
    learning_rate: 0.001
    num_epochs: 50
    max_clip_norm: null
    alpha: null
    seed: 0
wandb:
    logging: true
    project: local