defaults:
  - _self_
  - hydra: gpu_dev
  - override hydra/launcher: submitit_slurm

hydra:
  mode: MULTIRUN
  launcher:
    partition: dev_gpu_4
    timeout_min: 30
    mem_per_gpu: 8000
    gres: gpu:1

model:
    num_steps: 16
    c_dim: 2
    z_dim: 2
    h_dim: 64
    num_layers: 6
    non_linearity: GELU
    self_attn_num_heads: null
    cross_attn_num_heads: null
    max_context_size: null
    context_variant: mean
    noise_variant: free
    model_variant: dis
    contextual_schedules: true
training:
    batch_size: 128
    num_subtasks: 32
    num_val_tasks: 32
    num_samples: 100
    max_context_size: 10
    learning_rate: 0.001
    num_epochs: 5000
    alternating_ratio: null
    max_clip_norm: 1.0
    alpha: null
    seed: 0
wandb:
    logging: true
    project: cluster-dvi