defaults:
  - _self_
  - hydra: gpu_dev
  - override hydra/launcher: submitit_slurm

model:
    num_steps: 16
    c_dim: 2
    z_dim: 2
    h_dim: 64
    num_layers_enc: 6
    num_layers_ctrl: 6
    num_layers_sched: 6
    num_blocks: 1
    non_linearity: GELU
    self_attn_num_heads: null
    cross_attn_num_heads: null
    max_context_size: null
    context_variant: mean
    noise_variant: free
    model_variant: dis
    noise_max: 1
    noise_min: 0.01
    contextual_schedules: true
training:
    size: 128
    batch_size: 128
    num_subtasks: 32
    num_samples: 100
    max_context_size: 10
    learning_rate: 0.001
    num_epochs: 8000
    alternating_ratio: null
    max_clip_norm: 1.0
    alpha: null
    seed: 0
wandb:
    logging: true
    project: cluster-dvi