defaults:
  - _self_
  - hydra: gpu_dev
  - override hydra/launcher: submitit_slurm

hydra:
  mode: MULTIRUN
  launcher:
    partition: dev_gpu_4
    timeout_min: 30
    mem_per_gpu: 8000
    gres: gpu:1

benchmark:
    _target_: metalearning_benchmarks.line_sine1d_benchmark.LineSine1D
    n_datapoints_per_task: 64
    n_task: 4096
    output_noise: 0.1
    seed_noise: 1237
    seed_task: 1237
    seed_x: 123
common:
    x_dim: 1
    y_dim: 1
    c_dim: 2
    z_dim: 2
    h_dim: 64
    num_layers: 6
    non_linearity: SiLU
control_and_hyper_net:
    use_hyper_net: false
    is_cross_attentive: false
    num_heads: 1
decoder:
    has_lat_path: true
    has_det_path: false
    is_cross_attentive: false
    num_heads: 1
dvi_process:
    _target_: src.components.cdvi_process.DIS
    num_steps: 16
set_encoder:
    aggregation: max
    is_attentive: true
    use_context_size: false
training:
    batch_size: 128
    learning_rate: 0.0003
    num_epochs: 3000
    alternating_ratio: 0.2
    max_clip_norm: 0.5
    alpha: 1.0
wandb:
    logging: true
    project: cdvi-bml-alternating

