defaults:
  - _self_
  - hydra: gpu_dev
  - override hydra/launcher: submitit_slurm

hydra:
  mode: MULTIRUN
  launcher:
    partition: dev_gpu_4
    timeout_min: 30
    mem_per_gpu: 8000
    gres: gpu:1

benchmark:
    _target_: metalearning_benchmarks.line_sine1d_benchmark.LineSine1D
    n_datapoints_per_task: 64
    n_task: 4096
    output_noise: 0.1
    seed_noise: 1237
    seed_task: 1237
    seed_x: 123
common:
    x_dim: 1
    y_dim: 1
    c_dim: 2
    z_dim: 2
    h_dim: 64
    num_layers: 6
    non_linearity: GELU
    self_attn_num_heads: 1
    cross_attn_num_heads: 1
    max_context_size: null
    variant: aggr
    use_score: true
    aggregation: mean
    num_steps: 16
    contextual_schedules: true
training:
    batch_size: 128
    num_subtasks: 32
    num_val_tasks: 32
    sample_size: 100
    max_context_size: 16
    learning_rate: 0.0003
    num_epochs: 1000
    alternating_ratio: null
    max_clip_norm: null
    alpha: null
    seed: 0
wandb:
    logging: true
    project: cluster-test