defaults:
  - _self_
  - hydra: gpu_dev
  - override hydra/launcher: submitit_slurm

hydra:
  mode: MULTIRUN
  launcher:
    partition: dev_gpu_4
    timeout_min: 30
    mem_per_gpu: 4000
    gres: gpu:1

wandb:
  project: "dvi-for-bml"
  logging: true

training:
  num_epochs: 8000
  batch_size: 1024
  learning_rate: 3e-4
  max_clip_norm: 0.5
  alpha: 1.0
  
common:
  x_dim: 1
  y_dim: 1
  c_dim: 2
  z_dim: 2
  h_dim: 64
  num_layers: 6
  non_linearity: SiLU

dvi_process:
  _target_: src.components.dvi_process.DIS
  num_steps: 16

control_and_hyper_net:
  use_hyper_net: false
  is_cross_attentive: false
  num_heads: 1

set_encoder:
  aggregation: mean
  use_context_size: false
  is_attentive: true

decoder:
  has_lat_path: true
  has_det_path: false
  is_cross_attentive: false
  
benchmark:
  _target_: metalearning_benchmarks.line_sine1d_benchmark.LineSine1D
  n_task: 4096
  n_datapoints_per_task: 64
  output_noise: 0.1
  seed_task: 1237
  seed_x: 123
  seed_noise: 1237

